---
title: "The Storm is coming"
description: |
  A giant ship wedged across the Suez canal, record-breaking shipping rates, armadas of vessels waiting outside ports, covid-induced shutdowns: container shipping has rarely been as dramatic as it has in 2021. The average cost of shipping a standard large container (a 40-foot-equivalent unit, or feu) has surpassed $10,000, some four times higher than a year ago (see chart). The spot price for sending such a box from Shanghai to New York, which in 2019 would have been around $2,500, is now nearer $15,000. Securing a late booking on the busiest route, from China to the west coast of America, could cost $20,000.
author:
  - name: Lucas Bagge
    url: https://example.com/norajones
date: 10-27-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

```{r, layout="l-body-outset", preview=TRUE}
library(ggplot2)
ggplot(diamonds, aes(carat, price)) + geom_smooth() +
  facet_wrap(~ cut) +
  theme_minimal()
```
